server:
  port : 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH      
              allowedHeaders: "*"
            
      routes:
        - id: PERSONNEL-SERVICE
          uri: lb://PERSONNEL-SERVICE
          predicates:
            - Path=/Personnel/**
        - id: RDV-SERVICE
          uri: lb://RDV-SERVICE
          predicates:
            - Path=/Rdv/**
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
        - id: HOSPITALISATION-SERVICE
          uri: lb://HOSPITALISATION-SERVICE
          predicates:
            - Path=/hospitalisation/**
        - id: gestionDossierMedicaux
          uri: lb://gestionDossierMedicaux
          predicates:
            - Path=/dossierMedicaux/** 
      
      
         
            
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost